export const DEMO_STUDENTS = [
  { id:'s1', first_name:'Ahmet', last_name:'Yılmaz', gender:'erkek', birth_date:'2016-03-10', classroom_id:'c1' as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Mehmet', parent_last_name:'Yılmaz', parent_phone:'05321234567', mahalle:'Karacihan', sokak:'Çiçek Sok.', created_at:'2025-09-01', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s2', first_name:'Zeynep', last_name:'Kaya', gender:'kiz', birth_date:'2015-07-22', classroom_id:'c2' as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Ali', parent_last_name:'Kaya', parent_phone:'05331234567', mahalle:'Havzan', sokak:'Lale Sok.', created_at:'2025-09-01', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s3', first_name:'Mehmet', last_name:'Demir', gender:'erkek', birth_date:'2014-11-05', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Hasan', parent_last_name:'Demir', parent_phone:'05341234567', mahalle:'Karacihan', sokak:'Gül Sok.', created_at:'2025-09-02', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s4', first_name:'Ayşe', last_name:'Çelik', gender:'kiz', birth_date:'2017-02-14', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Veli', parent_last_name:'Çelik', parent_phone:'05351234567', mahalle:'Havzan', sokak:'Çiçek Sok.', created_at:'2025-09-03', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s5', first_name:'Yusuf', last_name:'Arslan', gender:'erkek', birth_date:'2015-08-30', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'İbrahim', parent_last_name:'Arslan', parent_phone:'05361234567', mahalle:'Karacihan', sokak:'Cumhuriyet Cad.', created_at:'2025-09-10', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s6', first_name:'Elif', last_name:'Şahin', gender:'kiz', birth_date:'2016-12-01', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Mustafa', parent_last_name:'Şahin', parent_phone:'05371234567', mahalle:'Havzan', sokak:'Gül Sok.', created_at:'2025-09-11', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s7', first_name:'Ömer', last_name:'Koç', gender:'erkek', birth_date:'2013-05-18', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Ramazan', parent_last_name:'Koç', parent_phone:'05381234567', mahalle:'Karacihan', sokak:'Lale Sok.', created_at:'2025-09-12', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s8', first_name:'Hatice', last_name:'Demir', gender:'kiz', birth_date:'2014-08-25', classroom_id:'c1' as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Osman', parent_last_name:'Demir', parent_phone:'05391234567', mahalle:'Meram', sokak:'Atatürk Cad.', created_at:'2025-09-13', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s9', first_name:'Ali', last_name:'Vural', gender:'erkek', birth_date:'2016-01-15', classroom_id:'c2' as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Kemal', parent_last_name:'Vural', parent_phone:'05301234567', mahalle:'Karacihan', sokak:'Çiçek Sok.', created_at:'2025-09-14', status:'approved' as 'pending'|'approved'|'rejected' },
  { id:'s10', first_name:'Yeni', last_name:'Başvuru1', gender:'erkek', birth_date:'2016-05-10', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Bekir', parent_last_name:'Yeni', parent_phone:'05399999901', mahalle:'Karacihan', sokak:'Gül Sok.', created_at:'2026-06-16', status:'pending' as 'pending'|'approved'|'rejected' },
  { id:'s11', first_name:'Yeni', last_name:'Başvuru2', gender:'kiz', birth_date:'2017-02-14', classroom_id:null as string|null, tc_no:'', city:'Konya', district:'Meram', parent_first_name:'Cemal', parent_last_name:'Yeni', parent_phone:'05399999902', mahalle:'Havzan', sokak:'Lale Sok.', created_at:'2026-06-16', status:'pending' as 'pending'|'approved'|'rejected' },
]

export const DEMO_CLASSROOMS = [
  { id:'c1', name:'Sabah Grubu', age_group:'7-9', capacity:20, student_count:2, teacher_id:'t1' as string|null, teacher_name:'Ahmet Öğretmen' as string|null, is_active:true },
  { id:'c2', name:'Öğleden Sonra', age_group:'10-12', capacity:18, student_count:2, teacher_id:null as string|null, teacher_name:null as string|null, is_active:true },
  { id:'c3', name:'Akşam Grubu', age_group:'10-14', capacity:15, student_count:0, teacher_id:'t2' as string|null, teacher_name:'Fatma Öğretmen' as string|null, is_active:true },
]

export const DEMO_TEACHERS = [
  { id:'t1', full_name:'Ahmet Öğretmen', phone:'05401234567', class_id:'c1' as string|null, class_name:'Sabah Grubu' as string|null, is_active:true, see_all:false, wa_connected:true },
  { id:'t2', full_name:'Fatma Öğretmen', phone:'05411234567', class_id:'c3' as string|null, class_name:'Akşam Grubu' as string|null, is_active:true, see_all:true, wa_connected:false },
]
